### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by davidgraeff** [karldaeubel/Anel-Power-Control-HOME#11]
Hey :)
Kannst du deinen Quellcode unter eine Lizenz stellen? Im Augenblick gibst du anderen github Nutzern ja implizit maximal die Erlaubnis zu forken, aber nichts zu verändern.

Viele Grüße,
David

**Comment by karldaeubel** [comment]
Vielen Dank für den Hinweis! 
Darf ich fragen wie du auf die App gestoßen bist und woher dein Interessee dafür kommt? 

Viele Grüße, Karl :)

**Comment by davidgraeff** [comment]
Hey :)

hab ich im Forum von Anel gesehen und dann genutzt ^^.
Mir fehlte nur noch eine Funktion und ich hatte deinen Quellcode
geforked und angefangen diesen zu erweitern bis mir das
mit der Lizenz auffiel. Dann hatte ich umgeschwenkt auf die
andere verfügbare Lösung auf SourceForge und hab diese
nun angepasst. Fand deine optisch besser gelungen. Die
SourceForge App nutzt allerdings die Möglichkeiten der Android
Plattform besser, wie etwa durch die Nutzung eines Hintergrund-Services für
das laufende Aktualisieren der Steckdosenzustände.

Ich hab meine erweiterte Version auf github unter
https://github.com/davidgraeff/netpowerctrl-sf-mirror liegen
und diese auch in den Play Store hochgeladen.
Vielleicht sollten wir (drei) gemeinsam an einer Lösung
arbeiten bzw. zumindest die Projekte zumindest untereinander
verlinken.

Viele Grüße, David
