### ISSUE TITLE
Design - Wallpaper

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/Anel-Power-Control-HOME#3]
- Ich hätte gern das erste Bild als default Hintergrundbild.
- (Optional): Auswahl eines Hintergrundbildes aus der eigenen Galerie.

Bild 1:
![htc_wallpaper_12](https://f.cloud.github.com/assets/3249687/62071/f392fa9a-5ccb-11e2-9263-719a6627577f.jpg)

Bild 2:
![htc-wallpaper](https://f.cloud.github.com/assets/3249687/62070/c5b9d846-5ccb-11e2-82eb-c9ec8e963bbc.jpg)

**Comment by karldaeubel** [comment]
Das default Hintergrundbild ist eingefügt: optional noch nicht erledigt!! -> bitte neue issue öffnen
