### ISSUE TITLE
Bug / Issue - Start der Config

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/Anel-Power-Control-HOME#5]
Nachdem starten der Config, öffnet wird sofort die die Tastatur angezeigt.
Bzw. Nachdem starten wird der Cursor ins erste Feld gesetzt.

Kan das unterdruckt werden und erst nach dem Klick auf ein Feld gestartet werden?

**Comment by karldaeubel** [comment]
der focus liegt weiterhin in dem 1. Feld, allerdings erscheint die Tastatur erst beim anklicken des gewünschten Feldes.
