### ISSUE TITLE
Function - Log

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/Anel-Power-Control-HOME#7]
Grund:
- um der Kommunikation zwischen "PowerControl" App und Steckerleiste besser zu verfolgen. 
- Vorgänge in der App werden für den User transparenter.

Wunsch: Es soll ein Log (Logbuch) erstellt werden, welches alle Vorgängen zwischen der app und der Leiste protokolliert. Weiterhin könnten auch alle wichtigen Änderungen (wie Änderung der Config) ins log geschrieben werden.

**Comment by karldaeubel** [comment]
Wie soll der User zugriff auf die Log haben? Kann man in Android den Ordner einer App durchsuchen? Nur vom PC zu lesen?!?!

**Comment by dennykorsukewitz** [comment]
wird eingestellt
