### ISSUE TITLE
Function - Status

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/Anel-Power-Control-HOME#8]
Notizen:
- Verbindung erfolgreich? - Verbindung zur Leiste  = true
- Status anzeigen... online ..offline.. konnte nicht erreichen.
- Status aktualisieren...als Dienst
- Anzeige der letzten Aktualisierung (Date)
- grüner, gelber, roter punkt....

**Comment by karldaeubel** [comment]
in dem Umfang nicht realisierbar, da die App nur mittels UDP sendet und empfängt. Ideen?

**Comment by karldaeubel** [comment]
möglicherweise Erweiterung auf tcp, da dann all dies machbar ist...

(Zukunftsmusik --- lalala :smirk: :notes: )

**Comment by dennykorsukewitz** [comment]
wird eingestellt
